import { defineConfig } from "vite";
import { resolve } from "node:path";

export default defineConfig({
  appType: "mpa",
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        howItWorks: resolve(__dirname, "how-it-works/index.html"),
        pricing: resolve(__dirname, "pricing/index.html"),
        safety: resolve(__dirname, "safety/index.html"),
        help: resolve(__dirname, "help/index.html"),
        become: resolve(__dirname, "become-a-shootr/index.html"),
        shootrs: resolve(__dirname, "shootrs/index.html"),
        shootrProfile: resolve(__dirname, "shootrs/hashimlafond/index.html"),
        alerts: resolve(__dirname, "waitlist/index.html"),
        terms: resolve(__dirname, "terms/index.html"),
        privacy: resolve(__dirname, "privacy/index.html"),
        communityStandards: resolve(__dirname, "community-standards/index.html"),
        accountDeletion: resolve(__dirname, "account-deletion/index.html"),
        signIn: resolve(__dirname, "sign-in/index.html"),
        signUp: resolve(__dirname, "sign-up/index.html"),
        forgotPassword: resolve(__dirname, "forgot-password/index.html"),
        verify: resolve(__dirname, "verify/index.html"),
        app: resolve(__dirname, "app/index.html"),
        appBook: resolve(__dirname, "app/book/index.html"),
        appSearch: resolve(__dirname, "app/search/index.html"),
        appRequest: resolve(__dirname, "app/request/index.html"),
        appMatches: resolve(__dirname, "app/matches/index.html"),
        appBookings: resolve(__dirname, "app/bookings/index.html"),
        appBookingDetail: resolve(__dirname, "app/bookings/demo-booking/index.html"),
        appBookingTracker: resolve(__dirname, "app/bookings/demo-booking/track/index.html"),
        appMoments: resolve(__dirname, "app/moments/index.html"),
        appMomentsDetail: resolve(__dirname, "app/moments/demo-booking/index.html"),
        appVault: resolve(__dirname, "app/vault/index.html"),
        appVaultDetail: resolve(__dirname, "app/vault/demo-booking/index.html"),
        appGallery: resolve(__dirname, "app/gallery/demo-booking/index.html"),
        appProfile: resolve(__dirname, "app/profile/index.html"),
        appProfileDeleteAccount: resolve(__dirname, "app/profile/delete-account/index.html"),
        appSupport: resolve(__dirname, "app/support/index.html"),
        shootr: resolve(__dirname, "shootr/index.html"),
        shootrOnboarding: resolve(__dirname, "shootr/onboarding/index.html"),
        shootrRequests: resolve(__dirname, "shootr/requests/index.html"),
        shootrJobs: resolve(__dirname, "shootr/jobs/index.html"),
        shootrJobDetail: resolve(__dirname, "shootr/jobs/demo-booking/index.html"),
        shootrDeliver: resolve(__dirname, "shootr/jobs/demo-booking/deliver/index.html"),
        shootrBookings: resolve(__dirname, "shootr/bookings/index.html"),
        shootrBookingDetail: resolve(__dirname, "shootr/bookings/demo-booking/index.html"),
        shootrAvailability: resolve(__dirname, "shootr/availability/index.html"),
        shootrMoments: resolve(__dirname, "shootr/moments/index.html"),
        shootrVault: resolve(__dirname, "shootr/vault/index.html"),
        shootrProfileApp: resolve(__dirname, "shootr/profile/index.html"),
        shootrPortfolio: resolve(__dirname, "shootr/portfolio/index.html"),
        shootrEarnings: resolve(__dirname, "shootr/earnings/index.html"),
        shootrSettings: resolve(__dirname, "shootr/settings/index.html"),
        shootrSupport: resolve(__dirname, "shootr/support/index.html"),
        admin: resolve(__dirname, "admin/index.html"),
        adminUsers: resolve(__dirname, "admin/users/index.html"),
        adminShootrs: resolve(__dirname, "admin/shootrs/index.html"),
        adminBusinesses: resolve(__dirname, "admin/businesses/index.html"),
        adminAgencies: resolve(__dirname, "admin/agencies/index.html"),
        adminBookings: resolve(__dirname, "admin/bookings/index.html"),
        adminGalleries: resolve(__dirname, "admin/galleries/index.html"),
        adminIncidents: resolve(__dirname, "admin/incidents/index.html"),
        adminPayments: resolve(__dirname, "admin/payments/index.html"),
        adminServiceAreas: resolve(__dirname, "admin/service-areas/index.html"),
        adminSettings: resolve(__dirname, "admin/settings/index.html"),
        adminCities: resolve(__dirname, "admin/cities/index.html"),
        adminAlerts: resolve(__dirname, "admin/waitlist/index.html")
      }
    }
  }
});
